---
name: Cﾄフﾄネin Corozanu
description: My English Corner
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
email: catalin@corozanu.ro
mailchimp-list: ''
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-menus
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  sal:
    name: Cﾄフﾄネin
    site: https://catalin.net
    avatar: "/assets/images/avatar1.jpg"
    bio: ''
    email: catalin@corozanu.ro
    twitter: https://twitter.com/corozanu
  jane:
    name: Jane
    site: https://www.wowthemes.net
    avatar: "/assets/images/avatar2.jpg"
    bio: Blogger, fashionista, love to explore new ideas and write on my morning coffee!
    email: fakemail@gmail.com
    twitter: https://twitter.com/wowthemesnet
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: sal
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
paginate: "10"
